version: '3'

services:
  gohat:
    container_name: gochat
    depends_on: 
      - redis
    image: gochat
    restart: always
    build:
      context: .
      dockerfile: build/package/Dockerfile
    ports:
      - "8080:8080"

  redis:
    container_name: redis
    restart: always
    image: redis
    volumes:
      - "redis:/var/lib/redis"
    ports:
      - "6379:6379"

volumes:
  redis:
    external: false