version: '3'

services:
  sgg-chat:
    container_name: sgg-chat
    depends_on: 
      - sgg-redis
    image: sgg-chat
    restart: always
    build:
      context: .
      dockerfile: build/package/Dockerfile
    ports:
      - "8080:8080"

  sgg-redis:
    container_name: sgg-redis
    restart: always
    image: redis
    volumes:
      - "redis:/var/lib/redis"
    ports:
      - "6379:6379"

volumes:
  redis:
    external: false